version: '3.8'

services:
  barberia-api:
    build: .
    container_name: barberia-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.wacfhjygmoagyegzupuz.supabase.co:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: fabricaudeA123*
      SPRING_APPLICATION_NAME: barberia-service
    restart: unless-stopped
    networks:
      - barberia-network

networks:
  barberia-network:
    driver: bridge
