services:
  barberia-api:
    build: .
    container_name: barberia-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - barberia-network

networks:
  barberia-network:
    driver: bridge
